version: 2
jobs:
  contributors-build-image:
    machine: true
    steps:
      - checkout
      - run: make contributors-build-image 
  
  contributors-build-website:
    machine: true
    steps:
      - checkout
      - run: make contributors-build-website

  deploy-website:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "matej.sima@gmail.com"
            git config --global user.name "Matej Sima"
            echo "machine github.com login maht0rz password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=maht0rz yarn run publish-gh-pages

workflows:
  version: 2
  default:
    jobs:
      - contributors-build-image
      - contributors-build-website
      - deploy-website
    

