version: 2

branch-develop-only: &branch-develop-only
  branches:
    only:
      - develop

jobs:
  contributors-build-image:
    machine: true
    steps:
      - checkout
      - run: make contributors-build-image

  test:
    # @TODO: run tests in a predefined environment, e.g. node 11
    machine: true
    steps:
      - checkout
      - run:
          name: CLI tests
          command: |
            make contributors-test

  deploy-npm-package:
    machine: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "64:a8:da:d6:2a:9a:ea:85:9e:4c:e3:22:c8:bd:36:1f"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Bump version
          # @TODO: It'd be ideal to have a separate user create releases
          command: |
            git config --global user.email "matej.sima@gmail.com"
            git config --global user.name "maht0rz"
            npm version prerelease --preid="pre-alpha" -m "Bumped pre-alpha version number to %s [skip ci]"
            git push origin feature/cli --tags
      - run:
          name: Publish package
          # @TODO: tag packages with branch names (?)
          command: npm publish --tag "pre-alpha"


  deploy-website:
    docker:
      - image: stovelabs/granary-contributors
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email $CIRCLE_USERNAME
            git config --global user.name $CIRCLE_USERNAME
            echo "machine github.com login maht0rz password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=maht0rz yarn run publish-gh-pages

workflows:
  version: 2
  default:
    triggers:
      - schedule:
          filters:
            <<: *branch-develop-only
    jobs:
      - contributors-build-image
      - test
      - deploy-npm-package:
          requires: 
            - contributors-build-image
            - test
      - deploy-website:
          requires: 
            - contributors-build-image
            - test
    

