version: 2

defaults:
  working_directory: ~/repo

jobs:
  contributors-build-image:
    machine: true
    steps:
      - checkout
      - run: make contributors-build-image

  test:
    # @TODO: run tests in a predefined environment, e.g. node 11
    machine: true
    steps:
      - checkout
      - run:
          name: CLI tests
          command: |
            make contributors-test

  deploy-npm-package:
    machine: true
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Bump version
          command: |
            npm version prerelease --preid=next -m "Bumped version number to %s [ci skip]"
            git config --global user.email $CIRCLE_USERNAME
            git config --global user.name $CIRCLE_USERNAME
            git push origin feature/cli
            git push --tags
      - run:
          name: Publish package
          # @TODO: tag packages with branch names (?)
          command: npm publish --tag next


  deploy-website:
    docker:
      - image: stovelabs/granary-contributors
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email $CIRCLE_USERNAME
            git config --global user.name $CIRCLE_USERNAME
            echo "machine github.com login maht0rz password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=maht0rz yarn run publish-gh-pages

workflows:
  version: 2
  default:
    jobs:
      - contributors-build-image
      - test
      - deploy-npm-package
      - deploy-website:
          requires: 
            - contributors-build-image
            - test
    

