version: 2

branch-develop-only: &branch-develop-only
  filters:
    branches:
      only: develop

jobs:
  contributors-build-image:
    machine: true
    steps:
      - checkout
      - run: make contributors-build-image

  install-dependencies:
    docker:
      - image: stovelabs/granary-contributors
    steps:
      - checkout
      - run:
          command: |
            npm i
      - save_cache:
          key: npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

  build:
    docker:
      - image: stovelabs/granary-contributors
    steps:
      - checkout
      - restore_cache:
          keys: 
            - npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Build
          command: |
            npm run build

  test:
    # @TODO: run tests in a predefined environment, e.g. node 11
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - npm-deps-{{ checksum "package-lock.json" }}
      - run:
          name: CLI tests
          command: |
            npm run test

  deploy-npm-package:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys: 
            - npm-deps-{{ checksum "package-lock.json" }}
      - add_ssh_keys:
          fingerprints:
            - "64:a8:da:d6:2a:9a:ea:85:9e:4c:e3:22:c8:bd:36:1f"
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Bump version
          # @TODO: It'd be ideal to have a separate user create releases
          command: |
            git config --global user.email "matej.sima@gmail.com"
            git config --global user.name "maht0rz"
            npm version prerelease --preid="pre-alpha" -m "Bumped pre-alpha version number to %s [skip ci]"
            git push origin develop --tags
      - run:
          name: Publish package
          # @TODO: tag packages with branch names (?)
          command: npm publish --tag "pre-alpha"


  deploy-website:
    docker:
      - image: stovelabs/granary-contributors
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email $CIRCLE_USERNAME
            git config --global user.name $CIRCLE_USERNAME
            echo "machine github.com login maht0rz password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=maht0rz yarn run publish-gh-pages

workflows:
  version: 2
  default:
    jobs:
      - contributors-build-image
      - install-dependencies:
          requires:
            - contributors-build-image
      - build:
          requires:
            - install-dependencies
      - test:
          requires:
            - build
      - deploy-npm-package:
          <<: *branch-develop-only
          requires: 
            - test
      - deploy-website:
          <<: *branch-develop-only
          requires: 
            - test
    

