version: 2
jobs:
  contributors-build-image:
    machine: true
    steps:
      - checkout
      - run: make contributors-build-image 
  
  contributors-build-website:
    machine: true
    steps:
      - checkout
      - run: make contributors-build-website

  deploy-website:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run:
          name: Deploying to GitHub Pages
          command: |
            git config --global user.email "<GITHUB_USERNAME>@users.noreply.github.com"
            git config --global user.name "<YOUR_NAME>"
            echo "machine github.com login <GITHUB_USERNAME> password $GITHUB_TOKEN" > ~/.netrc
            cd website && yarn install && GIT_USER=<GIT_USER> yarn run publish-gh-pages

workflows:
  version: 2
  contributors:
    build:
      - contributors-build-image
      - contributors-build-website
      - deploy-website

