version: '3'
services:
  node:
    container_name: sandboxnet_node
    image: tezos-environment-manager/sandbox-node
    command: bash -c 'sed -i -e 's/127.0.0.1/0.0.0.0/g' ./tezos/src/bin_node/tezos-sandboxed-node.sh; ./tezos/src/bin_node/tezos-sandboxed-node.sh 1'
    ports:
      - "18731:18731"
      - "8732:8732"
  tzscan:
    container_name: tzscan
    image: tezos-environment-manager/tzscan
    command: bash -c 'sh ./bin/init-tzscan'
    ports:
      - "8000:8000"
      - "8080:8080"